{{- if and (.Values.bullExporter.enabled) (gt (.Values.bullExporter.replicaCount | int) 1) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "soketi.bullExporterLabels" . | nindent 4 }}
  name: {{ include "soketi.fullname" . }}-bullmq-exporter
spec:
  selector:
    matchLabels:
      {{- include "soketi.bullExporterSelectorLabels" . | nindent 6 }}
  {{- if .Values.bullExporter.pdb.minAvailable }}
  minAvailable: {{ .Values.bullExporter.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.bullExporter.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.bullExporter.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
